#:schema node_modules/wrangler/config-schema.json
name = "ns"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
main = "./dist/worker/index.js"
assets = { directory = "./dist/public", binding = "ASSETS" }
route = { pattern = "ns.flashblaze.dev", custom_domain = true }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
NODE_VERSION = "20.17.0"
PNPM_VERSION = "9.12.0"
